version: '3'
services:
  mongodb:
    image: mongo:4.1
    container_name: mongo
    ports: 
      - "27018:27017"

  web:
    build: ./src/TodoApp
    ports:
      - "5000:80"
    depends_on:
            - mongodb
    container_name: web
